import PptxGenJS from "pptxgenjs";
import type { Report, AuditResult, EnhancedRecommendation } from "@/lib/db/types";
import { shouldShowRevenueDollars, stripDollarClaims } from "@/lib/reports/revenue-display";

const PURPLE = "7C3AED";
const DARK = "1E293B";
const GRAY = "6B7280";
const WHITE = "FFFFFF";
const LIGHT_BG = "F9FAFB";
const GREEN = "059669";
const BLUE = "2563EB";

const gradeColorMap: Record<string, string> = {
  Strong: "059669", Solid: "2563EB", Developing: "D97706", "Needs Attention": "EA580C",
  A: "059669", B: "2563EB", C: "F59E0B", D: "EF4444", F: "7C2D12",
};

function addFooter(slide: PptxGenJS.Slide) {
  slide.addText("Generated by Phantom Reach | phantomreach.io", {
    x: 0.5, y: 5.2, w: 9, h: 0.3, fontSize: 8, color: GRAY, fontFace: "Arial",
  });
}

export async function generateReportPPTX(report: Report): Promise<Buffer> {
  const auditResult = report.result as AuditResult | undefined;
  const input = report.input as any;
  const businessName = input?.businessName || "Business";
  const auditDate = new Date(report.created_at).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  const overallGrade = report.scores?.overall_grade || "N/A";
  const overallScore = report.scores?.overall_score || 0;
  const aiAnalysis = auditResult?.ai_analysis;
  const enhancedRecs = auditResult?.enhanced_recommendations;
  const showRevenueDollars = shouldShowRevenueDollars(auditResult?.revenue_impact);
  const displayRevenueText = (text: string | undefined) => (
    showRevenueDollars ? (text || "") : stripDollarClaims(text || "")
  );

  const pres = new PptxGenJS();
  pres.layout = "LAYOUT_16x9";
  pres.author = "Phantom Reach";

  const modules = [
    { key: "gbp_health", label: "GBP Health", result: auditResult?.gbp_health },
    { key: "review_sentiment", label: "Reviews", result: auditResult?.review_sentiment },
    { key: "website_performance", label: "Website", result: auditResult?.website_performance },
    { key: "tech_stack", label: "Tech Stack", result: auditResult?.tech_stack },
    { key: "social_presence", label: "Social", result: auditResult?.social_presence },
    { key: "citation_consistency", label: "Citations", result: auditResult?.citation_consistency },
    { key: "competitive_comparison", label: "Competitive", result: auditResult?.competitive_comparison },
    { key: "revenue_impact", label: showRevenueDollars ? "Revenue Impact" : "Business Impact", result: auditResult?.revenue_impact },
  ].filter((m) => m.result !== undefined);

  // ── Slide 1: Cover ───────────────────────────────────────
  const cover = pres.addSlide();
  cover.background = { fill: DARK };
  cover.addText("PHANTOM REACH", {
    x: 0.5, y: 0.8, w: 9, h: 0.6, fontSize: 36, bold: true, color: PURPLE,
    fontFace: "Arial", align: "center",
  });
  cover.addText("Business Intelligence Report", {
    x: 0.5, y: 1.5, w: 9, h: 0.4, fontSize: 16, color: "9CA3AF",
    fontFace: "Arial", align: "center",
  });
  cover.addShape(pres.ShapeType.rect, {
    x: 4.2, y: 2.1, w: 1.6, h: 0.04, fill: { color: PURPLE },
  });
  cover.addText(businessName, {
    x: 0.5, y: 2.5, w: 9, h: 0.8, fontSize: 28, bold: true, color: WHITE,
    fontFace: "Arial", align: "center",
  });
  // Grade circle
  cover.addShape(pres.ShapeType.ellipse, {
    x: 4.1, y: 3.4, w: 1.8, h: 1.8,
    fill: { color: gradeColorMap[overallGrade] || GRAY },
  });
  cover.addText(overallGrade, {
    x: 4.1, y: 3.55, w: 1.8, h: 1.2, fontSize: 48, bold: true, color: WHITE,
    fontFace: "Arial", align: "center", valign: "middle",
  });
  cover.addText(`Score: ${overallScore}/100`, {
    x: 4.1, y: 4.7, w: 1.8, h: 0.4, fontSize: 11, color: WHITE,
    fontFace: "Arial", align: "center",
  });
  cover.addText(auditDate, {
    x: 0.5, y: 5.1, w: 9, h: 0.3, fontSize: 11, color: "9CA3AF",
    fontFace: "Arial", align: "center",
  });

  // ── Slide 2: Executive Summary ───────────────────────────
  if (auditResult?.executive_summary) {
    const execSlide = pres.addSlide();
    execSlide.addText("Executive Summary", {
      x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 24, bold: true, color: DARK, fontFace: "Arial",
    });
    execSlide.addShape(pres.ShapeType.rect, {
      x: 0.5, y: 0.8, w: 2, h: 0.04, fill: { color: PURPLE },
    });
    const summaryText = typeof auditResult.executive_summary === "string"
      ? auditResult.executive_summary
      : [auditResult.executive_summary.verdict_context, ...(auditResult.executive_summary.core_story || [])].filter(Boolean).join(" ");
    execSlide.addText(displayRevenueText(summaryText).slice(0, 800), {
      x: 0.5, y: 1.0, w: 9, h: 3.5, fontSize: 13, color: "374151",
      fontFace: "Arial", lineSpacingMultiple: 1.4, valign: "top",
    });
    if (aiAnalysis?.cross_module_synthesis?.competitive_narrative) {
      execSlide.addShape(pres.ShapeType.roundRect, {
        x: 0.5, y: 4.3, w: 9, h: 0.8,
        fill: { color: "FAF5FF" },
        line: { color: "E9D5FF", width: 1 },
        rectRadius: 0.1,
      });
      execSlide.addText(displayRevenueText(aiAnalysis.cross_module_synthesis.competitive_narrative).slice(0, 300), {
        x: 0.7, y: 4.4, w: 8.6, h: 0.6, fontSize: 11, italic: true, color: DARK, fontFace: "Arial",
      });
    }
    addFooter(execSlide);
  }

  // ── Slide 3: Digital Health Scorecard ─────────────────────
  const scorecardSlide = pres.addSlide();
  scorecardSlide.addText("Digital Health Scorecard", {
    x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 24, bold: true, color: DARK, fontFace: "Arial",
  });
  scorecardSlide.addShape(pres.ShapeType.rect, {
    x: 0.5, y: 0.8, w: 2, h: 0.04, fill: { color: PURPLE },
  });

  modules.forEach((m, i) => {
    const col = i % 4;
    const row = Math.floor(i / 4);
    const x = 0.5 + col * 2.35;
    const y = 1.2 + row * 2;
    const gc = gradeColorMap[m.result?.grade || ""] || GRAY;

    scorecardSlide.addShape(pres.ShapeType.roundRect, {
      x, y, w: 2.1, h: 1.7, fill: { color: gc }, rectRadius: 0.1,
      shadow: { type: "outer", blur: 4, offset: 2, color: "000000", opacity: 0.1 },
    });
    scorecardSlide.addText(m.label, {
      x, y: y + 0.2, w: 2.1, h: 0.4, fontSize: 12, bold: true, color: WHITE,
      fontFace: "Arial", align: "center",
    });
    scorecardSlide.addText(m.result?.grade || "-", {
      x, y: y + 0.6, w: 2.1, h: 0.8, fontSize: 36, bold: true, color: WHITE,
      fontFace: "Arial", align: "center", valign: "middle",
    });
    scorecardSlide.addText(`${m.result?.score || 0}/100`, {
      x, y: y + 1.3, w: 2.1, h: 0.3, fontSize: 10, color: WHITE,
      fontFace: "Arial", align: "center",
    });
  });
  addFooter(scorecardSlide);

  // ── Slide 4: AI Analysis (if available) ──────────────────
  if (aiAnalysis) {
    // Causal chains
    if (aiAnalysis.cross_module_synthesis.causal_chains.length > 0) {
      const chainSlide = pres.addSlide();
      chainSlide.addText("Causal Chains", {
        x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 24, bold: true, color: DARK, fontFace: "Arial",
      });
      chainSlide.addShape(pres.ShapeType.rect, {
        x: 0.5, y: 0.8, w: 2, h: 0.04, fill: { color: "EF4444" },
      });
      chainSlide.addText("Problems that compound across modules", {
        x: 0.5, y: 0.9, w: 9, h: 0.3, fontSize: 11, color: GRAY, fontFace: "Arial",
      });

      aiAnalysis.cross_module_synthesis.causal_chains.slice(0, 3).forEach((chain, i) => {
        const y = 1.4 + i * 1.2;
        chainSlide.addShape(pres.ShapeType.roundRect, {
          x: 0.5, y, w: 9, h: 1.0,
          fill: { color: "FEF2F2" }, line: { color: "FECACA", width: 1 }, rectRadius: 0.08,
        });
        chainSlide.addText(displayRevenueText(chain.chain), {
          x: 0.7, y: y + 0.1, w: 8.6, h: 0.3, fontSize: 12, bold: true, color: DARK, fontFace: "Arial",
        });
        chainSlide.addText(displayRevenueText(chain.business_impact), {
          x: 0.7, y: y + 0.4, w: 8.6, h: 0.25, fontSize: 10, color: "374151", fontFace: "Arial",
        });
        chainSlide.addText(`Fix: ${chain.fix_sequence}`, {
          x: 0.7, y: y + 0.7, w: 8.6, h: 0.2, fontSize: 10, bold: true, color: GREEN, fontFace: "Arial",
        });
      });
      addFooter(chainSlide);
    }

    // Priority Action Plan
    if (aiAnalysis.priority_action_plan.length > 0) {
      const actionSlide = pres.addSlide();
      actionSlide.addText("Priority Action Plan", {
        x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 24, bold: true, color: DARK, fontFace: "Arial",
      });
      actionSlide.addShape(pres.ShapeType.rect, {
        x: 0.5, y: 0.8, w: 2, h: 0.04, fill: { color: PURPLE },
      });

      aiAnalysis.priority_action_plan.slice(0, 4).forEach((action, i) => {
        const y = 1.2 + i * 1.0;
        // Number circle
        actionSlide.addShape(pres.ShapeType.ellipse, {
          x: 0.5, y, w: 0.45, h: 0.45, fill: { color: PURPLE },
        });
        actionSlide.addText(String(i + 1), {
          x: 0.5, y, w: 0.45, h: 0.45, fontSize: 14, bold: true, color: WHITE,
          fontFace: "Arial", align: "center", valign: "middle",
        });
        actionSlide.addText(action.action, {
          x: 1.1, y, w: 8.4, h: 0.3, fontSize: 13, bold: true, color: DARK, fontFace: "Arial",
        });
        actionSlide.addText(`ROI: ${displayRevenueText(action.expected_roi)}  |  ${action.timeframe}${action.unlocks ? `  |  Unlocks: ${displayRevenueText(action.unlocks)}` : ""}`, {
          x: 1.1, y: y + 0.3, w: 8.4, h: 0.25, fontSize: 10, color: GRAY, fontFace: "Arial",
        });
      });
      addFooter(actionSlide);
    }
  }

  // ── Module Detail Slides ─────────────────────────────────
  for (const module of modules) {
    if (!module.result) continue;
    const slide = pres.addSlide();
    const gc = gradeColorMap[module.result.grade] || GRAY;

    slide.addText(module.label, {
      x: 0.5, y: 0.3, w: 7, h: 0.5, fontSize: 24, bold: true, color: DARK, fontFace: "Arial",
    });
    // Grade badge
    slide.addShape(pres.ShapeType.roundRect, {
      x: 8.2, y: 0.3, w: 1.3, h: 0.5, fill: { color: gc }, rectRadius: 0.08,
    });
    slide.addText(`${module.result.grade} (${module.result.score})`, {
      x: 8.2, y: 0.3, w: 1.3, h: 0.5, fontSize: 14, bold: true, color: WHITE,
      fontFace: "Arial", align: "center", valign: "middle",
    });
    slide.addShape(pres.ShapeType.rect, {
      x: 0.5, y: 0.8, w: 2, h: 0.04, fill: { color: gc },
    });

    // Findings
    if (module.result.findings?.length) {
      slide.addText("Key Findings", {
        x: 0.5, y: 1.0, w: 4.3, h: 0.3, fontSize: 14, bold: true, color: DARK, fontFace: "Arial",
      });
      const findings = module.result.findings.slice(0, 4).map((f) => ({
        text: displayRevenueText(f), options: { bullet: true, breakLine: true, fontSize: 11, color: "374151" as string, fontFace: "Arial" },
      }));
      slide.addText(findings as any, {
        x: 0.5, y: 1.4, w: 4.3, h: 2.5, valign: "top",
      });
    }

    // Recommendations
    if (module.result.recommendations?.length) {
      slide.addText("Recommendations", {
        x: 5.2, y: 1.0, w: 4.3, h: 0.3, fontSize: 14, bold: true, color: DARK, fontFace: "Arial",
      });
      const recs = module.result.recommendations.slice(0, 4).map((r) => ({
        text: displayRevenueText(r), options: { bullet: true, breakLine: true, fontSize: 11, color: "374151" as string, fontFace: "Arial" },
      }));
      slide.addText(recs as any, {
        x: 5.2, y: 1.4, w: 4.3, h: 2.5, valign: "top",
      });
    }

    addFooter(slide);
  }

  // ── Recommendations Slide ────────────────────────────────
  const recs = enhancedRecs?.length ? enhancedRecs.slice(0, 5) : (auditResult?.recommendations || []).slice(0, 5);
  if (recs.length > 0) {
    const recSlide = pres.addSlide();
    recSlide.addText(enhancedRecs?.length ? "AI-Enhanced Recommendations" : "Top Recommendations", {
      x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 24, bold: true, color: DARK, fontFace: "Arial",
    });
    recSlide.addShape(pres.ShapeType.rect, {
      x: 0.5, y: 0.8, w: 2, h: 0.04, fill: { color: PURPLE },
    });

    recs.forEach((rec, i) => {
      const enhanced = rec as EnhancedRecommendation;
      const y = 1.1 + i * 0.8;
      recSlide.addShape(pres.ShapeType.ellipse, {
        x: 0.5, y, w: 0.4, h: 0.4, fill: { color: PURPLE },
      });
      recSlide.addText(String(i + 1), {
        x: 0.5, y, w: 0.4, h: 0.4, fontSize: 12, bold: true, color: WHITE,
        fontFace: "Arial", align: "center", valign: "middle",
      });
      recSlide.addText(rec.title, {
        x: 1.0, y, w: 8.5, h: 0.25, fontSize: 13, bold: true, color: DARK, fontFace: "Arial",
      });
      const meta = [
        `${rec.impact.toUpperCase()} Impact`,
        `${rec.effort.toUpperCase()} Effort`,
        ...(enhanced.timeframe ? [enhanced.timeframe] : []),
      ].join("  |  ");
      recSlide.addText(meta, {
        x: 1.0, y: y + 0.3, w: 8.5, h: 0.2, fontSize: 10, color: GRAY, fontFace: "Arial",
      });
    });
    addFooter(recSlide);
  }

  // ── Thank You Slide ──────────────────────────────────────
  const tySlide = pres.addSlide();
  tySlide.background = { fill: DARK };
  tySlide.addText("Thank You", {
    x: 0.5, y: 1.5, w: 9, h: 0.8, fontSize: 36, bold: true, color: WHITE,
    fontFace: "Arial", align: "center",
  });
  tySlide.addShape(pres.ShapeType.rect, {
    x: 4.2, y: 2.5, w: 1.6, h: 0.04, fill: { color: PURPLE },
  });
  tySlide.addText(`Report for ${businessName}`, {
    x: 0.5, y: 2.8, w: 9, h: 0.4, fontSize: 16, color: "9CA3AF",
    fontFace: "Arial", align: "center",
  });
  tySlide.addText("phantomreach.io", {
    x: 0.5, y: 3.5, w: 9, h: 0.4, fontSize: 14, color: PURPLE,
    fontFace: "Arial", align: "center",
  });

  const output = await pres.write({ outputType: "nodebuffer" });
  return Buffer.from(output as ArrayBuffer);
}
